# Generated by Django 5.1.2 on 2024-10-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('date_of_birth', models.CharField(max_length=50, primary_key='date_of_birth', serialize=False)),
                ('fathers_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('customerid', models.IntegerField()),
                ('accountdetails', models.IntegerField()),
            ],
        ),
    ]
